apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  labels:
    app: microservice
  namespace: deployment-demo
  annotations:
    monitoring: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microserice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
        - image: eeafp/microsvc:0.1
          name: microsvc
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "1Gi"
              cpu: "300m"
            requests:
              memory: "1Gi"
              cpu: "300m"
