apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice
  name: microservice
  namespace: deployment-demo
spec:
  ports:
    - nodePort: 30500
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: microservice
  type: NodePort
